#ifndef __CONFIG_H
#define __CONFIG_H

#define SYSCLK_FREQUENCY_HZ 168000000
#define SYSTICK_FREQUENCY_HZ 1000
#define MICROSECONDS_PER_SECOND 1000000

#define MS_CALIBRACION_LINEA 2000
#define LECTURA_MAXIMO_SENSORES_LINEA 4096
#define LECTURA_MINIMO_SENSORES_LINEA 0
#define LINEA_BLANCA 2
#define LINEA_NEGRA 1
#define LINEA LINEA_NEGRA


#endif